
import JavaCourseworkUP918631.*;
import JavaCourseworkUP918631.pizza_attributes.PizzaCrust;
import JavaCourseworkUP918631.pizza_attributes.PizzaSauce;
import JavaCourseworkUP918631.pizza_attributes.PizzaSize;
import JavaCourseworkUP918631.pizza_attributes.PizzaTopping;

public class EditPizzaForm extends javax.swing.JFrame {

    private final OrderForm orderForm;
    private final Order order;
    public int pizzaPos; //Current Pizza

    private Pizza getCurrentlySelectedPizza() {

        //Convert string to equivalent enum value
        PizzaSize pizzaSize = PizzaSize.valueOf(size_cb.getSelectedItem().toString());
        PizzaCrust pizzaCrust = PizzaCrust.valueOf(crust_cb.getSelectedItem().toString());
        PizzaTopping pizzaTopping1 = PizzaTopping.valueOf(topping1_cb.getSelectedItem().toString());
        PizzaTopping pizzaTopping2 = PizzaTopping.valueOf(topping2_cb.getSelectedItem().toString());
        PizzaSauce pizzaSauce = PizzaSauce.valueOf(sauce_cb.getSelectedItem().toString());

        return new Pizza(pizzaSize, pizzaCrust, pizzaSauce, pizzaTopping1, pizzaTopping2);
    }

    private void updateInvoice() {

        //Get's order of first Pizza in Arraylist
        jTextArea1.setText(order.get(pizzaPos).getInvoice());
    }

    public EditPizzaForm(OrderForm orderForm) {

        this.orderForm = orderForm;
        this.order = new Order();

        for (int i = 0; i < orderForm.getOrder().getPizzaCount(); i++) {
            order.addPizza(orderForm.getOrder().get(i));
        }

        pizzaPos = 0;

        initComponents();
        populateFields();
        updateInvoice();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        ok_btn = new javax.swing.JButton();
        delete_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        crust_cb = new javax.swing.JComboBox<>();
        size_cb = new javax.swing.JComboBox<>();
        topping1_cb = new javax.swing.JComboBox<>();
        topping2_cb = new javax.swing.JComboBox<>();
        sauce_cb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        left_btn = new javax.swing.JButton();
        right_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(205, 475));
        setSize(new java.awt.Dimension(200, 475));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel5.setText("SAUCE");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        ok_btn.setText("OK");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        delete_btn.setText("DELETE PIZZA");
        delete_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("SIZE");

        crust_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "THIN", "DEEP", "STUFFED" }));
        crust_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_itemStateChanged(evt);
            }
        });

        size_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SMALL", "MEDIUM", "LARGE" }));
        size_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_itemStateChanged(evt);
            }
        });

        topping1_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "OLIVES", "EXTRA_CHEESE", "CHILLI", "PEPPERONI", "MUSHROOM", "ROCKET", "JALAPENOS", "ONION", "ANCHOVY" }));
        topping1_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_itemStateChanged(evt);
            }
        });

        topping2_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "OLIVES", "EXTRA_CHEESE", "CHILLI", "PEPPERONI", "MUSHROOM", "ROCKET", "JALAPENOS", "ONION", "ANCHOVY" }));
        topping2_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_itemStateChanged(evt);
            }
        });

        sauce_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOMATO", "PESTO" }));
        sauce_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cb_itemStateChanged(evt);
            }
        });

        jLabel2.setText("CRUST");

        jLabel3.setText("TOPPING 1");

        jLabel4.setText("TOPPING 2");

        left_btn.setText("<");
        left_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                left_btnActionPerformed(evt);
            }
        });

        right_btn.setText(">");
        right_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                right_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(left_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(right_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(ok_btn))
                            .addComponent(delete_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(crust_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topping1_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topping2_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sauce_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(size_cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(size_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(crust_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topping1_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topping2_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sauce_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ok_btn)
                    .addComponent(right_btn)
                    .addComponent(left_btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(delete_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        saveAndReturnToOrderForm();
    }//GEN-LAST:event_ok_btnActionPerformed

    private void delete_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_btnActionPerformed
        
        order.deletePizza(pizzaPos);
        saveAndReturnToOrderForm();
    }//GEN-LAST:event_delete_btnActionPerformed

    private void saveAndReturnToOrderForm() {
        orderForm.setOrder(order);
        
        orderForm.update();

        orderForm.setVisible(true);
        setVisible(false);
        dispose();
    }

    private void populateFields() {

        Pizza pizza = order.get(pizzaPos);

        size_cb.setSelectedItem(pizza.getSize().toString());
        crust_cb.setSelectedItem(pizza.getCrust().toString());
        topping1_cb.setSelectedItem(pizza.getTopping1().toString());
        topping2_cb.setSelectedItem(pizza.getTopping2().toString());
        sauce_cb.setSelectedItem(pizza.getSauce().toString());
    }

    private void addToPizzaPos(int delta) {

        pizzaPos += delta;

        while (pizzaPos < 0) {
            pizzaPos += order.getPizzaCount();
        }

        pizzaPos %= order.getPizzaCount();
    }

    private void right_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_right_btnActionPerformed

        addToPizzaPos(1);
        populateFields();
        updateInvoice();
    }//GEN-LAST:event_right_btnActionPerformed

    private void left_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_left_btnActionPerformed

        addToPizzaPos(-1);
        populateFields();
        updateInvoice();
    }//GEN-LAST:event_left_btnActionPerformed

    private void cb_itemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cb_itemStateChanged

        order.set(pizzaPos, getCurrentlySelectedPizza());
        updateInvoice();
    }//GEN-LAST:event_cb_itemStateChanged

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed

        orderForm.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> crust_cb;
    private javax.swing.JButton delete_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton left_btn;
    private javax.swing.JButton ok_btn;
    private javax.swing.JButton right_btn;
    private javax.swing.JComboBox<String> sauce_cb;
    private javax.swing.JComboBox<String> size_cb;
    private javax.swing.JComboBox<String> topping1_cb;
    private javax.swing.JComboBox<String> topping2_cb;
    // End of variables declaration//GEN-END:variables
}
