
import JavaCourseworkUP918631.*;
import JavaCourseworkUP918631.pizza_attributes.PizzaCrust;
import JavaCourseworkUP918631.pizza_attributes.PizzaSauce;
import JavaCourseworkUP918631.pizza_attributes.PizzaSize;
import JavaCourseworkUP918631.pizza_attributes.PizzaTopping;

public class NewPizzaForm extends javax.swing.JFrame {
    
    private final OrderForm orderForm;
    
    private Pizza getCurrentlySelectedPizza() {
        
        //Convert string to equivalent enum value
        PizzaSize pizzaSize = PizzaSize.valueOf(size_cb.getSelectedItem().toString());
        PizzaCrust pizzaCrust = PizzaCrust.valueOf(crust_cb.getSelectedItem().toString());
        PizzaTopping pizzaTopping1 = PizzaTopping.valueOf(topping1_cb.getSelectedItem().toString());
        PizzaTopping pizzaTopping2 = PizzaTopping.valueOf(topping2_cb.getSelectedItem().toString());
        PizzaSauce pizzaSauce = PizzaSauce.valueOf(sauce_cb.getSelectedItem().toString());

        return new Pizza(pizzaSize, pizzaCrust, pizzaSauce, pizzaTopping1, pizzaTopping2);
    }

    private void makeNewOrder() {

        orderForm.getOrder().addPizza(getCurrentlySelectedPizza());
        orderForm.update();
        orderForm.setVisible(true);
        setVisible(false);
        dispose();
    }
    
    private void updateInvoice(){

        jTextArea1.setText(getCurrentlySelectedPizza().getInvoice());
    }

    public NewPizzaForm(OrderForm orderForm) {
        
        this.orderForm = orderForm;
        
        initComponents();
        
        updateInvoice();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        crust_cb = new javax.swing.JComboBox<>();
        size_cb = new javax.swing.JComboBox<>();
        topping1_cb = new javax.swing.JComboBox<>();
        topping2_cb = new javax.swing.JComboBox<>();
        sauce_cb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        cancel_btn = new javax.swing.JButton();
        add_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("SIZE");

        crust_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "THIN", "DEEP", "STUFFED" }));
        crust_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxValueChanged(evt);
            }
        });

        size_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SMALL", "MEDIUM", "LARGE" }));
        size_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxValueChanged(evt);
            }
        });

        topping1_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "OLIVES", "EXTRA_CHEESE", "CHILLI", "PEPPERONI", "MUSHROOM", "ROCKET", "JALAPENOS", "ONION", "ANCHOVY" }));
        topping1_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxValueChanged(evt);
            }
        });

        topping2_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NONE", "OLIVES", "EXTRA_CHEESE", "CHILLI", "PEPPERONI", "MUSHROOM", "ROCKET", "JALAPENOS", "ONION", "ANCHOVY" }));
        topping2_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxValueChanged(evt);
            }
        });

        sauce_cb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TOMATO", "PESTO" }));
        sauce_cb.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBoxValueChanged(evt);
            }
        });

        jLabel2.setText("CRUST");

        jLabel3.setText("TOPPING 1");

        jLabel4.setText("TOPPING 2");

        jLabel5.setText("SAUCE");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        cancel_btn.setText("CANCEL");
        cancel_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_btnActionPerformed(evt);
            }
        });

        add_btn.setText("ADD PIZZA");
        add_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(topping2_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(topping1_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(crust_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(size_cb, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sauce_cb, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancel_btn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(add_btn)
                                .addGap(3, 3, 3)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(size_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(crust_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topping1_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(topping2_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sauce_cb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel_btn)
                    .addComponent(add_btn))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancel_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_btnActionPerformed
        
        orderForm.setVisible(true);
        setVisible(false);
        dispose();
    }//GEN-LAST:event_cancel_btnActionPerformed

    private void add_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_btnActionPerformed
        makeNewOrder();
    }//GEN-LAST:event_add_btnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
        orderForm.setVisible(true);
    }//GEN-LAST:event_formWindowClosed

    private void comboBoxValueChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBoxValueChanged
        
        updateInvoice();
    }//GEN-LAST:event_comboBoxValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_btn;
    private javax.swing.JButton cancel_btn;
    private javax.swing.JComboBox<String> crust_cb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JComboBox<String> sauce_cb;
    private javax.swing.JComboBox<String> size_cb;
    private javax.swing.JComboBox<String> topping1_cb;
    private javax.swing.JComboBox<String> topping2_cb;
    // End of variables declaration//GEN-END:variables
}
